
====================
== NVIDIA Modulus ==
====================

NVIDIA Release 24.09 (build 18526012)
Modulus PyPi Version 0.9.0 (Git Commit: eb01d2a)
Modulus Sym PyPi Version 1.7.0 (Git Commit: 249b76a)
Container image Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Copyright (c) 2014-2024 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 12.6 driver version 560.35.03 with kernel driver version 550.144.03.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

job is starting on gpua055.delta.ncsa.illinois.edu
Python 3.10.12
/usr/local/lib/python3.10/dist-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
/usr/local/lib/python3.10/dist-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Warp 1.3.3 initialized:
   CUDA Toolkit 12.5, Driver 12.6
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA A100-SXM4-40GB" (39 GiB, sm_80, mempool enabled)
   Kernel cache:
     /u/wzhong/.cache/warp/1.3.3
Creating data loaders...
Data loaders created: Train=2460, Val=410, Test=1230
Creating data loaders...
Not finding in path 2
Loading pretrained model ...
No trained model
model training ...
Failed to load /work/hdd/bdsy/wzhong/processed_data/driver/graph2212.pt: PytorchStreamReader failed reading zip archive: failed finding central directory
Module modulus.models.figconvnet.warp_neighbor_search 7da5518 load on device 'cuda:0' took 708.22 ms  (compiled)
Epoch 1/400, Loss: 2.77258872
validating
Current best validation errs by now: 0.818401680341581
Failed to load /work/hdd/bdsy/wzhong/processed_data/driver/graph2212.pt: PytorchStreamReader failed reading zip archive: failed finding central directory
Epoch 2/400, Loss: 0.04317629
Failed to load /work/hdd/bdsy/wzhong/processed_data/driver/graph2212.pt: PytorchStreamReader failed reading zip archive: failed finding central directory
Epoch 3/400, Loss: 0.03991357
validating
Current best validation errs by now: 0.7168758526080992
Failed to load /work/hdd/bdsy/wzhong/processed_data/driver/graph2212.pt: PytorchStreamReader failed reading zip archive: failed finding central directory
Epoch 4/400, Loss: 0.02455368
Failed to load /work/hdd/bdsy/wzhong/processed_data/driver/graph2212.pt: PytorchStreamReader failed reading zip archive: failed finding central directory
Epoch 5/400, Loss: 0.01795559
validating
Current best validation errs by now: 0.5048018458412915
Traceback (most recent call last):
  File "/FC/main.py", line 195, in <module>
    train_grid_model(args, model, optimizer, device, train_loader, val_loader, scale_factor, epochs=400)
  File "/FC/utils.py", line 53, in train_grid_model
    loss.backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.21 GiB. GPU 
